import { exadevConfig } from "@exadev/eslint-config";
import raycast from "@raycast/eslint-plugin";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import globals from "globals";

/**
 * Raycast's own rules (command titles, manifest hygiene) run on top of the shared ExaDev config so `ray lint` and the Raycast store review agree with it.
 */
export default exadevConfig(
  {},
  {
    ignores: [
      "node_modules",
      ".raycast",
      "coverage",
      "reports",
      ".stryker-tmp",
      ".turbo",
      // Generated by `ray build` from package.json.
      "raycast-env.d.ts",
      "pnpm-lock.yaml",
    ],
  },
  {
    languageOptions: {
      parserOptions: {
        project: ["./tsconfig.json"],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },
  },
  ...raycast.configs.recommended,
  {
    // Scoped to JS and TS: an unscoped block also matches the JSON files the shared config lints under a different language, which never registers this plugin.
    files: ["**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs}"],
    rules: {
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
    },
  },
  eslintPluginPrettierRecommended,
);
